import lastmod from '../data/page-lastmod.json';

/**
 * The date a non-article page last changed, so every page type can carry
 * dateModified and not just the collections.
 *
 * The map is generated by scripts/ai-visibility/page-lastmod.mjs from git and
 * committed, because Vercel clones shallow and cannot recompute it.
 */
const map = lastmod as Record<string, string>;

export function lastmodFor(pathnameOrUrl: string): string | null {
  let pathname = pathnameOrUrl;
  try {
    if (/^https?:\/\//.test(pathnameOrUrl)) pathname = new URL(pathnameOrUrl).pathname;
  } catch {
    /* fall through with the raw value */
  }
  if (!pathname.startsWith('/')) pathname = `/${pathname}`;
  if (!pathname.endsWith('/')) pathname = `${pathname}/`;
  return map[pathname] ?? null;
}
